services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      TRAEFIK_DASHBOARD_CREDENTIALS: ${TRAEFIK_DASHBOARD_CREDENTIALS}
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/stacks/network/traefik/data/traefik.yaml:/traefik.yaml:ro
      - /opt/stacks/network/traefik/data/acme.json:/acme.json
      - /opt/stacks/network/traefik/data/config.yaml:/config.yaml:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.rule=Host(`traefik-dashboard.local.thepasture.uk`)
      - traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}
      - traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.traefik.middlewares=traefik-https-redirect
      - traefik.http.routers.traefik-secure.entrypoints=https
      - traefik.http.routers.traefik-secure.rule=Host(`traefik-dashboard.local.thepasture.uk`)
      - traefik.http.routers.traefik-secure.middlewares=traefik-auth
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik-secure.tls.certresolver=cloudflare
      - traefik.http.routers.traefik-secure.tls.domains[0].main=local.thepasture.uk
      - traefik.http.routers.traefik-secure.tls.domains[0].sans=*.local.thepasture.uk
      - traefik.http.routers.traefik-secure.service=api@internal
  
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id
    container_name: pocket-id
    restart: unless-stopped
    env_file: .env
    # ports:
    #   - 3000:80
    volumes:
      - /opt/stacks/network/pocketid/data:/app/backend/data
    healthcheck:
      test: curl -f http://localhost/healthz
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    labels:
      - traefik.enable=true
      - traefik.http.routers.pocket-id.rule=Host(`pocketid.local.thepasture.uk`)
        || Host(`pocketid.thepasture.uk`)
      - traefik.http.routers.pocket-id.entrypoints=https
      - traefik.http.routers.pocket-id.tls=true
      - traefik.http.services.pocket-id.loadbalancer.server.port=80
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TRUST_PROXY=true
      - PUBLIC_APP_URL=https://pocketid.thepasture.uk
  
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v3
    # ports:
    #   - 3055:3000
    container_name: tinyauth
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - SECRET=gTFaOBAGBVe5gp6hKxw6BFgJVjFXSeRy
      - APP_URL=https://tinyauth.thepasture.uk
      - USERS=cole:$$2a$$10$$5sq.p4ICVPYvNvW2mA8pruyBwWuU7IbCJcq176.McSWyjPkZI7g.G
      - OAUTH_AUTO_REDIRECT=generic
      - GENERIC_CLIENT_ID=304bfe15-d9b7-4979-a99d-31a595f1e96d
      - GENERIC_CLIENT_SECRET=troThBBbJ3MqQ2uguI67f995yGzv1V9Z
      - GENERIC_AUTH_URL=https://pocketid.thepasture.uk/authorize
      - GENERIC_TOKEN_URL=https://pocketid.thepasture.uk/api/oidc/token
      - GENERIC_USER_URL=https://pocketid.thepasture.uk/api/oidc/userinfo
      - GENERIC_SCOPES=openid email profile groups
      - GENERIC_NAME=Pocket ID
    labels:
      - traefik.enable=true
      - traefik.http.routers.tinyauth.rule=Host(`tinyauth.local.thepasture.uk`) || Host(`tinyauth.thepasture.uk`)
      - traefik.http.middlewares.tinyauth.forwardauth.address=http://tinyauth:3000/api/auth/traefik
      - traefik.http.routers.tinyauth.entrypoints=https
      - traefik.http.routers.tinyauth.tls=true
      - traefik.http.services.tinyauth.loadbalancer.server.port=3000
networks:
  proxy:
    external: true
