version: "3.8"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - /home/serveradmin/docker_volumes/uptime-kuma/data:/app/data
      #ports:
      #- 3001:3001
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.kuma.rule=Host(`kuma.local.thepasture.uk`)
      - traefik.http.routers.kuma.entrypoints=https
      - traefik.http.routers.kuma.tls=true
      - traefik.http.services.kuma.loadbalancer.server.port=3001
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    container_name: audiobookshelf
    networks:
      - proxy
    volumes:
      - /tank/media/books:/books
      - /tank/media/audiobooks:/audiobooks
      - /opt/stacks/web-apps/audiobookshelf/config:/config
      - /opt/stacks/web-apps/audiobookshelf/metadata:/metadata
    environment:
      - TZ=America/Los_Angeles
    labels:
      - traefik.enable=true
      - traefik.http.routers.audiobooks.rule=Host(`audiobooks.local.thepasture.uk`) || Host(`audiobooks.thepasture.uk`)
      - traefik.http.routers.audiobooks.entrypoints=https
      - traefik.http.routers.audiobooks.tls=true
      - traefik.http.services.audiobooks.loadbalancer.server.port=80
  actual-budget:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual-budget-main
    ports:
      - 5006:5006
    networks:
      - proxy
    environment:
      # Uncomment any of the lines below to set configuration options.
      # - ACTUAL_HTTPS_KEY=/data/selfhost.key
      # - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      - ACTUAL_PORT=5006
      - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
      # !! If you are not using any of these options, remove the 'environment:' tag entirely.
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - /opt/stacks/web-apps/actual-budget/data:/data
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.actual-budget.rule=Host(`budget.local.thepasture.uk`) || Host(`budget.thepasture.uk`)
      - traefik.http.routers.actual-budget.entrypoints=https
      - traefik.http.routers.actual-budget.tls=true
      - traefik.http.services.actual-budget.loadbalancer.server.port=5006
networks:
  proxy:
    external: true
